version: "2"
services:
  fastdfs:
    container_name: fastdfs
    image: deravo/fastdfs
    command: all
    network_mode: host
    environment:
      - TRACKER_SERVER=172.16.20.153:22122
    volumes:
      - /var/fdfs:/var/fdfs
  #tracker:
  #  container_name: tracker
  #  image: deravo/fastdfs
  #  command: tracker
  #  network_mode: host
  #  volumes:   
  #    - /var/fdfs:/var/fdfs    
  #storage:
  #  container_name: storage
  #  image: deravo/fastdfs
  #  command: storage
  #  network_mode: host  
  #  environment:
  #    - TRACKER_SERVER=172.16.20.153:22122
  #  volumes: 
  #    - /var/fdfs:/var/fdfs
  #storage0:
  #  container_name: storage0
  #  command: storage
  #  network_mode: host
  #  environment:
  #    - TRACKER_SERVER=172.16.20.153:22122
  #    - PORT=23001
  #    - DATA_PATH=storage0
  #    - GROUP=group1
  #  volumes:
  #    - /var/fdfs:/var/fdfs
